/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sisteminformasidesa.DatabaseCRUD;
/**
 *
 * @author Lenovo
 */
public class Register extends javax.swing.JFrame {

        DatabaseCRUD db;

    public Register() {
        initComponents();
    db = new DatabaseCRUD(); // Inisialisasi koneksi database
    
    try {
        Statement s = db.koneksi.createStatement(); // Membuat statement SQL
        String sql = "SELECT nik, username, nama_lengkap, tanggal_lahir, no_handphone, email, password FROM register";
        ResultSet r = s.executeQuery(sql); // Eksekusi query

        // Iterasi hasil query
        while (r.next()) {
            // Ambil data dari kolom database dan tambahkan ke tabel
            Object[] row_data = {
                r.getString("nik"),
                r.getString("username"),
                r.getString("nama_lengkap"),
                r.getDate("tanggal_lahir"), // Format date
                r.getString("no_handphone"),
                r.getString("email"),
                r.getString("password")
            };

            
            // Debug log (opsional)
            System.out.println("NIK : " + r.getString("nik"));
            System.out.println("Username : " + r.getString("username"));
            System.out.println("Nama Lengkap : " + r.getString("nama_lengkap"));
            System.out.println("Tanggal Lahir : " + r.getDate("tanggal_lahir"));
            System.out.println("No Handphone : " + r.getString("no_handphone"));
            System.out.println("Email : " + r.getString("email"));
            System.out.println("Password : " + r.getString("password"));
        }
        
    } catch (SQLException e) {
        // Tangani kesalahan koneksi atau query
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxt_namaLengkap = new javax.swing.JTextField();
        jTxt_username = new javax.swing.JTextField();
        jTxt_email = new javax.swing.JTextField();
        jButton_konfirmasi = new javax.swing.JButton();
        jPassword_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxt_nik = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxt_noHandphone = new javax.swing.JTextField();
        jDateChooser1_tanggalLahir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM REGISTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Password");

        jTxt_namaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_namaLengkapActionPerformed(evt);
            }
        });

        jTxt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_usernameActionPerformed(evt);
            }
        });

        jButton_konfirmasi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_konfirmasi.setText("Konfirmasi");
        jButton_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_konfirmasiActionPerformed(evt);
            }
        });

        jPassword_password.setText("jPasswordField1");
        jPassword_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_passwordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal Lahir");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("NIK");

        jTxt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_nikActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("No Handphone");

        jTxt_noHandphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_noHandphoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_konfirmasi)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_nik)
                    .addComponent(jTxt_username)
                    .addComponent(jTxt_namaLengkap)
                    .addComponent(jTxt_noHandphone)
                    .addComponent(jTxt_email)
                    .addComponent(jPassword_password, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(jDateChooser1_tanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_namaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1_tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(jTxt_noHandphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassword_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton_konfirmasi)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPassword_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword_passwordActionPerformed

    private void jTxt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_usernameActionPerformed

    private void jTxt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_nikActionPerformed

    private void jTxt_noHandphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_noHandphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_noHandphoneActionPerformed

    private void jTxt_namaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_namaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_namaLengkapActionPerformed

    private void jButton_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_konfirmasiActionPerformed
        // TODO add your handling code here:
                // Mengambil data dari form
        String nik = jTxt_nik.getText();
        String username = jTxt_username.getText();
        String namaLengkap = jTxt_namaLengkap.getText();
        String email = jTxt_email.getText();
        String password = new String(jPassword_password.getPassword());
        String noHandphone = jTxt_noHandphone.getText();
        java.util.Date tanggalLahir = jDateChooser1_tanggalLahir.getDate();

        // Validasi input
        if (nik.isEmpty() || username.isEmpty() || namaLengkap.isEmpty() || email.isEmpty() || password.isEmpty() || noHandphone.isEmpty() || tanggalLahir == null) {
            JOptionPane.showMessageDialog(this, "Harap isi semua data.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Format tanggal lahir ke dalam format SQL
        java.sql.Date sqlTanggalLahir = new java.sql.Date(tanggalLahir.getTime());

        // Query SQL untuk menyimpan data
        String sql = "INSERT INTO register (nik, username, nama_lengkap, email, password, no_handphone, tanggal_lahir) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try {
            PreparedStatement ps = db.koneksi.prepareStatement(sql);
            ps.setString(1, nik);
            ps.setString(2, username);
            ps.setString(3, namaLengkap);
            ps.setString(4, email);
            ps.setString(5, password);
            ps.setString(6, noHandphone);
            ps.setDate(7, sqlTanggalLahir);

            // Eksekusi query
            int rowsInserted = ps.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Registrasi berhasil.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Registrasi gagal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_konfirmasiActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_konfirmasi;
    private com.toedter.calendar.JDateChooser jDateChooser1_tanggalLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword_password;
    private javax.swing.JTextField jTxt_email;
    private javax.swing.JTextField jTxt_namaLengkap;
    private javax.swing.JTextField jTxt_nik;
    private javax.swing.JTextField jTxt_noHandphone;
    private javax.swing.JTextField jTxt_username;
    // End of variables declaration//GEN-END:variables
}
